require 'rubygems'
require 'thread'
require 'csv'
require 'twitter'
require 'marky_markov'
require 'yaml'
require 'thor'

require 'ebooks/version'
require 'ebooks/core_ext'
require 'ebooks/config'
require 'ebooks/twitter'
require 'ebooks/markov_dictionary'
require 'ebooks/generator'
require 'ebooks/corpora/twitter_corpus'
